name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with: 
        version: 14
        
    - name: Github action for  Yarn or npm
      uses: linchpin/action-build-yarn-npm@master
      with:
          # npm/yarn command
        cmd: install #npm start or yarn start(by default it happen automatically)
    
    - name: Creating build
      run: npm build
    
    
    - name: installing surge  
      run: npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://btcmp2020class2.surge.sh/ --token ${{secrets.MYTOKEN}}